### ISSUE TITLE
2 Bugs + Fixes

### ISSUE THREAD

**Issue by xNS5** [NathanielMotus/UmlClassEditor#2]
When first installing the application, if the user were to hit "Delete project" when there are none, the app crashes. I was able to replicate this on both a Samsung Galaxy S8+ and a Galaxy Tab S7. 

The error is coming from IOUtils:94 where it tries to iterate through a null ~~File[] array~~ File object and subsequently throws a NullPointerException, and there's an error in UmlType:184 with error "End of input at character 0 ". The latter doesn't crash the application.

I've gone through and fixed both bugs, but I don't have permission to create new branches and submit a PR for review. Would love to get the fixes added to the main project!

Edit: I modified the function to instead take in a `File[]` array instead of an object, makes it a tad easier to check for zero files.

**Comment by NathanielMotus** [comment]
Thank you for your help ! It's strange you can't make a PR... As far as I know (but I still learn to swim in Git), you just have to pull the project to your local repo, change code and then make your PR.

If it still doesn't work, I'll dig it further so that you can change code.

**Comment by xNS5** [comment]
I'm attempting to create a new branch in your repo, but judging from the last PR it seems like people are forking + submitting a PR once fixes have been made. I can fork the repo and submit a PR that way if that's the preferred method.
